# Site settings
title: Grayscale
email: sendad.sali3@domain.com
url: https://example.github.io
description: " This is my webpage."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#219ab3'

# Footer settings
footer: Senad Sali

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: linkedin
    url: https://al.linkedin.com/in/senad-salihu-621554128
  - title: facebook
    url: https://web.facebook.com/senad.salihu.e

# Build settings
markdown: kramdown
permalink: pretty
